---
- name: set self hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '127\.0\.1\.1.*'
    line: "127.0.1.1 {{ inventory_hostname }}"
- name: donot use systemd/resolve
  lineinfile:
    dest: /etc/systemd/resolved.conf
    state: present
    backrefs: yes
    regexp: .*DNSStubListener=yes
    line: DNSStubListener=no
- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: yes
  when: resolv_link.changed
