---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: set sshd_config PasswordAuthentication no
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^.?PasswordAuthentication.*"
    replace: "PasswordAuthentication no"
- name: set sshd_config UsePAM yes
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^.?UsePAM.*"
    replace: "UsePAM yes"
- name: set sshd_config UseDNS no
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^.?UseDNS.*"
    replace: "UseDNS no"
- name: restart sshd
  service:
    name: sshd
    state: restarted
