---
- name: add the overlay module
  modprobe:
    name: overlay
    state: present

- name: create containerd modulelist
  lineinfile:
    create: yes
    path: /etc/modules-load.d/containerd.conf
    line: "overlay"

- name: set firmware configs
  lineinfile:
    dest: /boot/config.txt
    line: "{{ item }}"
  with_items:
    - temp_limit=70
    - dtparam=act_led_trigger=default-on
    - dtparam=pwr_led_trigger=none
    - gpu_mem=32
    - arm_freq=900
    - over_voltage=5
  register: firm_configs
- block:
    - name: reboot for apply firmware config.txt
      shell: reboot
      async: 1
      poll: 0
      ignore_errors: true
      changed_when: false
    - name: wait for reboot
      wait_for_connection:
        delay: 30
        timeout: 300
  when: firm_configs.changed

- name: update packages releaseinfo
  shell: apt-get update --allow-releaseinfo-change

- name: apt remove avahi-daemon
  apt:
    name: avahi-daemon
    state: absent
    purge: yes
