network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
  wifis:
    wlan0:
      dhcp4: false
      dhcp6: false
      access-points:
        "__WIFI_SSID":
          hidden: true
          password: "__WIFI_PASSWD"
  bonds:
    bond0:
      interfaces:
        - eth0
        - wlan0
      parameters:
        arp-interval: 1000
        arp-ip-targets: [192.168.3.1]
  bridges:
    br0:
      interfaces:
        - bond0
      dhcp4: false
      dhcp6: false
      addresses:
        - __IPADDRESS
      gateway4: 192.168.3.1
      nameservers:
        search: [__DOMAIN]
        addresses:
          - 192.168.3.250
          - 8.8.8.8
