---
# - include: "global.yaml"

- include: "ubuntu.yaml"
  when:
    - ansible_distribution == 'Ubuntu'
    - network_config is defined
# - include: "raspio.yaml"
#   when: "ansible_distribution == 'Debian'"
