---
- name: add containerd gpg-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: get lsb_release -cs
  shell: lsb_release -cs
  changed_when: false
  register: lsb_name
- name: add containerd repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/debian {{ lsb_name.stdout }} stable
    state: present
    filename: containerd
- name: add container backend
  apt:
    update_cache: yes
    name: containerd.io
- block:
    - name: present /etc/containerd directory
      file:
        dest: /etc/containerd
        state: directory
- block:
    - name: present config.toml
      copy:
        src: config.toml
        dest: /etc/containerd/
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
    - name: edit config.toml zone-info for {{ global_zonename }}
      replace:
        path: /etc/containerd/config.toml
        regexp: "__ZONE_NAME"
        replace: "{{ global_zonename }}"
- name: start containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes
    enabled: yes
