---
- name: configure keepalived.conf for infra
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items:
    - { regexp: "__INSTANCE_NAME", line: "VI_0" }
    - { regexp: "__ROUTER_ID", line: "50" }
    - { regexp: "__VIP_ADDR", line: "192.168.3.250/24" }
    - { regexp: "__PRIORITY", line: "50" }
