---
- name: configure keepalived.conf for masters
  replace:
    path: /etc/keepalived/keepalived.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  with_items:
    - { regexp: "__INSTANCE_NAME", line: "VI_1" }
    - { regexp: "__ROUTER_ID", line: "51" }
    - { regexp: "__VIP_ADDR", line: "192.168.3.10/24" }
    - { regexp: "__PRIORITY", line: "50" }
