---
# jetsonの場合は予めnvidia-docker2をインストールする
- block:
    - name: add nvidia-docker gpg-key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present
    - name: get param distribution
      shell: |
        . /etc/os-release;
        echo $ID$VERSION_ID
      register: distribution
      changed_when: false
    - name: get nvidia-docker context
      uri:
        url: https://nvidia.github.io/nvidia-docker/{{ distribution.stdout }}/nvidia-docker.list
        return_content: yes
      register: repositories
    - name: add nvidia-docker repository
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: nvidia-docker
      with_items: "{{ repositories.content.splitlines() }}"
      when: item is match("^(?!#)")
    - name: add nvidia-docker2
      apt:
        name: nvidia-docker2
        update_cache: yes
  when:
    - "board_type == 'jetson'"
