all:
  vars:
    first_master: master01
  children:
    infra:
      hosts:
        infra01:
          ansible_host: "192.168.3.250"
          network_config: "bind"
          gitlab_restore: false
    kubernetes:
      children:
        master:
          hosts:
            master01:
              ansible_host: "192.168.3.11"
            master02:
              ansible_host: "192.168.3.12"
            master03:
              ansible_host: "192.168.3.13"
        worker:
          children:
            gluster:
              hosts:
                node01:
                  ansible_host: "192.168.3.21"
                node02:
                  ansible_host: "192.168.3.22"
                node03:
                  ansible_host: "192.168.3.23"
    edge:
      children:
        camera:
          hosts:
            edge01:
              ansible_host: "192.168.3.31"
              use_swapfile: true
            # edge02:
            #   ansible_host: "192.168.3.32"
            #   use_swapfile: true
