- hosts: all
  become: true
  roles:
    - common
    - resolv
    - network

- import_playbook: sandbox-setup.yaml
- import_playbook: infra-setup.yaml
- import_playbook: gluster-setup.yaml
- import_playbook: k8s-setup.yaml
- import_playbook: edges-setup.yaml

- hosts: all
  become: true
  roles:
    - swapon
