- hosts: all
  become: true
  roles:
    - common
    - resolv
    - network

## DNSサーバ
- hosts: infra
  become: true
  roles:
    - bind9
    - gitlab
    - glusterfs/client

- hosts: gluster
  become: true
  roles:
    - keepalive
    - glusterfs/server

- hosts: master
  become: true
  roles:
    - keepalive

- hosts: kubernetes
  become: true
  roles:
    - glusterfs/client
    - docker
    - kubernetes/install
    - kubernetes/build
    - { role: kubernetes/configure, when: "inventory_hostname == first_master" }

- hosts: edge
  become: true
  roles:
    - network
    - docker
    - docker-compose

- hosts: camera
  become: true
  roles:
    - camera

- hosts: all
  become: true
  roles:
    - swapon
