---
- name: check gitlab installed
  package_facts:
    manager: auto
## gitlabがインストール済みでない場合のみ実行
- block:
    - name: get gitlab context
      uri:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
        return_content: yes
      register: gitlab_script
    - name: run gitlab script
      shell:
        cmd: bash
        stdin: "{{ gitlab_script.content }}"
    - name: install gitlab
      apt:
        name: gitlab-ce=13.11.4-ce.0
        update_cache: yes
  when: '"gitlab-ce" not in ansible_facts.packages'
- name: check gitlab.rb exists
  stat:
    path: /etc/gitlab/gitlab.rb
  register: diff_ex
- name: present gitlab.rb as temp
  copy:
    src: gitlab.rb
    dest: /etc/gitlab/gitlab.rb.tmp
    owner: root
    group: root
# バックアップデバイスの探索
- block:
    - name: get backup volume for gluster brick
      shell: blkid | grep /dev/sda | awk -F\" '{ print $2 }'
      register: uuid
      changed_when: uuid.stdout != ""
    - block:
        - name: create mountpoint for backup
          file:
            path: /bak
            state: directory
        - name: mount backup volume
          mount:
            name: "/bak"
            src: "UUID={{ uuid.stdout }}"
            fstype: "ext4"
            opts: defaults,nofail
            state: mounted
      when: uuid.changed
    - name: edit gitlab.rb backup_path
      lineinfile:
        dest: "/etc/gitlab/gitlab.rb.tmp"
        regexp: "^gitlab_rails.'backup_path'."
        state: absent
      when: not uuid.changed
- block:
    - name: edit gitlab.rb zone-info
      replace:
        path: /etc/gitlab/gitlab.rb.tmp
        regexp: "__ZONE_NAME"
        replace: "{{ global_zonename }}"
    - name: check network-setting renewed
      shell: diff /etc/gitlab/gitlab.rb.tmp /etc/gitlab/gitlab.rb > /dev/null
      register: diff_ch
      changed_when: diff_ch.rc == 1
      failed_when: diff_ch.rc == 2
      when: diff_ex.stat.exists
    - name: renew gitlab.rb if changed
      shell: cp /etc/gitlab/gitlab.rb.tmp /etc/gitlab/gitlab.rb
      register: diff_renew
      changed_when: true
      when: not diff_ex.stat.exists or diff_ch.changed
    - name: clear temp file
      file:
        path: /etc/gitlab/gitlab.rb.tmp
        state: absent
- name: gitlab reconfigure
  shell: gitlab-ctl reconfigure
  when: diff_renew.changed
